// AUTO-GENERATED by scripts/gen-cms-types.mjs — do not edit by hand.
// Source: Strapi schemas in ../cms/src/{components,api}.
// Regenerate with `npm run gen:types`; `npm run check:types` fails on drift.
/* eslint-disable */


// ─── Components ──────────────────────────────────────────────────────────────

/** One slice of a dashboard scope's figures — the KPIs, monthly bars, funnel, state and payer tables for a period, a state ('' = all) and a workflow */
export interface DashboardFigureSet {
  period: "last_12_months" | "financial_year" | "last_quarter" | "last_30_days";
  state?: string;
  workflow: "all" | "eligibility" | "preauth" | "claim";
  kpis: ElementsKpi[];
  months: ElementsMonthBar[];
  funnel: ElementsFunnelItem[];
  states: ElementsStateRow[];
  payers: ElementsPayerRow[];
}

/** Network actor label with a marker shape */
export interface ElementsActorChip {
  label: string;
  marker?: "dot" | "square" | "diamond" | "ring" | "dash";
}

/** Label + value + horizontal bar percentage */
export interface ElementsBarItem {
  label: string;
  value?: string;
  pct?: number;
}

/** Title + note card */
export interface ElementsBenefitCard {
  title: string;
  description?: string;
}

/** Audience-specific column of benefit cards */
export interface ElementsBenefitColumn {
  audienceLabel?: string;
  heading: string;
  cards: ElementsBenefitCard[];
}

/** One line of a list — a release highlight, a breaking change, an outline point */
export interface ElementsBullet {
  text: string;
}

/** Checklist line */
export interface ElementsCheckItem {
  text: string;
}

/** A short text label */
export interface ElementsChip {
  label: string;
}

/** Row of the NHCX statistics table */
export interface ElementsDashboardRow {
  label: string;
  sublabel?: string;
  integrators?: string;
  hospitals?: string;
  preauthRequests?: string;
  claimRequests?: string;
  highlight?: boolean;
}

/** Sidebar group of documentation links */
export interface ElementsDocNavGroup {
  label: string;
  links: ElementsLink[];
}

/** Spec/download card with abstract icon */
export interface ElementsDownloadCard {
  icon?: "square" | "circle" | "diamond" | "pill" | "square-filled" | "circle-filled" | "square-dashed" | "gradient";
  title: string;
  description?: string;
  meta?: string;
  url?: string;
}

/** Downloads table row */
export interface ElementsDownloadRow {
  name: string;
  note?: string;
  runtime?: string;
  size?: string;
  format?: string;
  url?: string;
}

/** Upcoming event with timestamp label */
export interface ElementsEvent {
  when: string;
  title: string;
}

/** Capability card with an abstract icon */
export interface ElementsFeature {
  icon?: "square" | "circle" | "diamond" | "pill" | "square-filled" | "circle-filled" | "square-dashed" | "gradient";
  title: string;
  description?: string;
}

/** Titled column of footer links */
export interface ElementsFooterColumn {
  title: string;
  links: ElementsLink[];
}

/** One segment of the claim status funnel */
export interface ElementsFunnelItem {
  label: string;
  count?: string;
  pct?: number;
  tone?: "brand" | "brand-light" | "amber" | "muted";
}

/** One timestamped update on an incident */
export interface ElementsIncidentUpdate {
  at: string;
  text: string;
  state?: "investigating" | "identified" | "monitoring" | "resolved";
}

/** Dashboard KPI card with delta chip */
export interface ElementsKpi {
  label: string;
  value: string;
  suffix?: string;
  delta?: string;
  deltaGood?: boolean;
  foot?: string;
}

/** A label + URL pair, optionally styled as a button */
export interface ElementsLink {
  label: string;
  url?: string;
  style?: "primary" | "secondary" | "ghost";
}

/** Big value + title + supporting note */
export interface ElementsMetricCard {
  value: string;
  title?: string;
  description?: string;
}

/** One bar of the monthly claims chart */
export interface ElementsMonthBar {
  label: string;
  value?: string;
  submittedPct?: number;
  settledPct?: number;
}

/** Network participants table row */
export interface ElementsParticipantRow {
  role: string;
  live?: string;
  added?: string;
}

/** Payer-wise settlement table row */
export interface ElementsPayerRow {
  name: string;
  role?: string;
  claims?: string;
  preauth?: string;
  sla?: string;
}

/** FAQ question and answer, grouped by topic, optionally pointing at a documentation page */
export interface ElementsQa {
  topic?: string;
  question: string;
  answer: string;
  docs?: string;
}

/** Page metadata */
export interface ElementsSeo {
  metaTitle: string;
  metaDescription?: string;
}

/** Small value + label pair */
export interface ElementsStatItem {
  value: string;
  label?: string;
}

/** State-wise settlement table row */
export interface ElementsStateRow {
  name: string;
  claims?: string;
  amount?: string;
  preauth?: string;
  sla?: string;
  pct?: number;
}

/** Numbered process step */
export interface ElementsStep {
  tag?: string;
  title: string;
  description?: string;
  highlighted?: boolean;
}

/** A titled link with a one-line description — the landing "Start here" row and the DevTools "Inside the console" list. A `devtools:` URL (devtools:/apis) resolves to the DevTools console address in global.devtoolsUrl. */
export interface ElementsTile {
  title: string;
  description?: string;
  url: string;
}

/** Status tracker step with progress state */
export interface ElementsTimelineStep {
  label: string;
  detail?: string;
  state?: "done" | "active" | "todo";
}

/** Accent-titled short trait */
export interface ElementsTrait {
  title: string;
  description?: string;
}

/** Claim workflow endpoint table row */
export interface ElementsWorkflowRow {
  workflow: string;
  endpoint?: string;
  callback?: string;
}

/** Link to an API catalogue entry by slug */
export interface PlaybookApiRef {
  slug: string;
  label: string;
  note?: string;
  required?: boolean;
}

/** Persona-specific API list and implementation order */
export interface PlaybookPersona {
  key: "provider" | "payer" | "tpa";
  label: string;
  intro?: string;
  mandatoryApis: PlaybookApiRef[];
  implementationOrder: ElementsStep[];
}

/** One stage of the integration playbook */
export interface PlaybookStage {
  key: "onboarding" | "sandbox_access" | "mandatory_apis" | "implementation_order" | "certification" | "production_readiness";
  title: string;
  intro?: string;
  docsLink?: string;
  items: ElementsStep[];
}

/** Badge + title + actor chips */
export interface SectionsActors {
  __component: "sections.actors";
  anchor?: string;
  badge?: string;
  title: string;
  actors: ElementsActorChip[];
}

/** Grid of capability features */
export interface SectionsCapabilities {
  __component: "sections.capabilities";
  anchor?: string;
  title: string;
  features: ElementsFeature[];
}

/** Closing call to action */
export interface SectionsCta {
  __component: "sections.cta";
  anchor?: string;
  title: string;
  primaryCta?: ElementsLink;
  secondaryCta?: ElementsLink;
}

/** Dashboard teaser with statistics table */
export interface SectionsDashboardPromo {
  __component: "sections.dashboard-promo";
  anchor?: string;
  eyebrow?: string;
  title: string;
  description?: string;
  cta?: ElementsLink;
  tableTitle?: string;
  updatedAt?: string;
  rows: ElementsDashboardRow[];
  secondaryLink?: ElementsLink;
}

/** NHCX developer tooling promo panel (formerly Integration kit) */
export interface SectionsDevtools {
  __component: "sections.devtools";
  anchor?: string;
  badgeText?: string;
  title: string;
  description?: string;
  metricLabel?: string;
  metricValue?: string;
  metricUnit?: string;
  metricNote?: string;
  steps: ElementsStep[];
  primaryCta?: ElementsLink;
  secondaryCta?: ElementsLink;
  metaChips: ElementsChip[];
}

/** Questions and answers */
export interface SectionsFaq {
  __component: "sections.faq";
  anchor?: string;
  title: string;
  items: ElementsQa[];
}

/** Headline hero with the NHCX network diagram */
export interface SectionsHero {
  __component: "sections.hero";
  anchor?: string;
  badgeText?: string;
  badgeAccent?: string;
  title: string;
  subtitle?: string;
  primaryCta?: ElementsLink;
  secondaryCta?: ElementsLink;
  windowTitle?: string;
  providersLabel?: string;
  providers: ElementsChip[];
  payersLabel?: string;
  payers: ElementsChip[];
  hubTitle?: string;
  hubTag?: string;
  hubCaption?: string;
  startLabel?: string;
  startTiles: ElementsTile[];
}

/** UTI NHCX connector promo panel */
export interface SectionsIntegrationKit {
  __component: "sections.integration-kit";
  anchor?: string;
  badgeText?: string;
  title: string;
  description?: string;
  metricLabel?: string;
  metricValue?: string;
  metricUnit?: string;
  metricNote?: string;
  steps: ElementsStep[];
  primaryCta?: ElementsLink;
  secondaryCta?: ElementsLink;
  metaChips: ElementsChip[];
}

/** Network figures + supporting stats (static, from the CMS) */
export interface SectionsLiveStats {
  __component: "sections.live-stats";
  anchor?: string;
  badge?: string;
  counterStart?: number;
  counterLabel?: string;
  todayStart?: number;
  todayLabel?: string;
  stats: ElementsStatItem[];
  asOf?: string;
}

/** HMIS → NHCX → payer auto-adjudication flow */
export interface SectionsPipeline {
  __component: "sections.pipeline";
  anchor?: string;
  eyebrow?: string;
  title: string;
  intro?: string;
  sourceTag?: string;
  sourceTitle?: string;
  sourceCodeLines?: unknown;
  sourceNote?: string;
  leftPacketLabel?: string;
  rightPacketLabel?: string;
  hubTitle?: string;
  hubTag?: string;
  hubNote?: string;
  targetTag?: string;
  targetTitle?: string;
  targetChecks: ElementsCheckItem[];
  targetNote?: string;
  metrics: ElementsMetricCard[];
}

/** Provider vs payer benefit columns + traits */
export interface SectionsSplitBenefits {
  __component: "sections.split-benefits";
  anchor?: string;
  eyebrow?: string;
  title: string;
  intro?: string;
  columns: ElementsBenefitColumn[];
  traits: ElementsTrait[];
}

/** Onboarding process steps */
export interface SectionsSteps {
  __component: "sections.steps";
  anchor?: string;
  title: string;
  intro?: string;
  steps: ElementsStep[];
  cta?: ElementsLink;
}

// ─── Content types ───────────────────────────────────────────────────────────

/** Copy for the sandbox access application form at /apply */
export interface ApplyPage {
  seo?: ElementsSeo;
  eyebrow?: string;
  title?: string;
  intro?: string;
  useCaseOptions?: unknown;
  documentsNote?: string;
  consentText?: string;
  submitLabel?: string;
  successTitle?: string;
  successText?: string;
  errorText?: string;
  privacyTitle?: string;
  privacyText?: string;
  termsTitle?: string;
  termsText?: string;
}

/** Network dashboard copy and shared datasets (scope datasets live in Dashboard scopes) */
export interface DashboardPage {
  seo?: ElementsSeo;
  eyebrow?: string;
  title?: string;
  dataAsOf?: string;
  csvLabel?: string;
  monthlyTitle?: string;
  funnelTitle?: string;
  responseTitle?: string;
  responseTimes: ElementsStatItem[];
  statesTitle?: string;
  payersTitle?: string;
  specialitiesTitle?: string;
  specialities: ElementsBarItem[];
  participantsTitle?: string;
  participants: ElementsParticipantRow[];
  settlementTitle?: string;
  settlement: ElementsBarItem[];
  applicationsTitle?: string;
  applicationsNote?: string;
  feedNote?: string;
  feedLinks: ElementsLink[];
}

/** One dashboard dataset (all claims, government schemes, private insurers & TPAs) with its figure sets per period/state/workflow and where the figures came from */
export interface DashboardScope {
  key: string;
  label: string;
  note?: string;
  rank?: number;
  source: "sample" | "exchange_feed" | "manual";
  asOf?: string;
  figures: DashboardFigureSet[];
}

/** Site-wide chrome: government ribbon, masthead, navigation and footer */
export interface Global {
  ribbonText?: string;
  ribbonLinks: ElementsLink[];
  brandTitle?: string;
  brandSubtitle?: string;
  nhaAlt?: string;
  nhaHref?: string;
  abdmAlt?: string;
  abdmHref?: string;
  pmjayAlt?: string;
  pmjayHref?: string;
  navLinks: ElementsLink[];
  applyCta?: ElementsLink;
  footerBrandTitle?: string;
  footerBlurb?: string;
  newsletterTitle?: string;
  newsletterBlurb?: string;
  footerColumns: ElementsFooterColumn[];
  copyright?: string;
  legalLinks: ElementsLink[];
  subFooterLinks: ElementsLink[];
  devtoolsUrl?: string;
  /** Where the documentation site lives; the `docs:` scheme resolves here. */
  docsUrl?: string;
  logoUrl: string;
  nhaLogoUrl: string;
  abdmLogoUrl: string;
  pmjayLogoUrl: string;
  nhaLogoWhiteUrl: string;
}

/** A service incident with its timeline; drives uptime on /status */
export interface Incident {
  title: string;
  service?: Service;
  startedAt: string;
  resolvedAt?: string;
  impact: "none" | "minor" | "major" | "critical";
  summary?: string;
  updates: ElementsIncidentUpdate[];
}

/** UTI NHCX connector download page */
export interface IntegrationKitPage {
  seo?: ElementsSeo;
  badgeText?: string;
  title?: string;
  description?: string;
  primaryCta?: ElementsLink;
  secondaryCta?: ElementsLink;
  metaChips: ElementsChip[];
  buildLabel?: string;
  buildVersion?: string;
  buildReleased?: string;
  buildSpec?: string;
  buildChangelog?: ElementsLink;
  flowSource?: string;
  flowConnector?: string;
  flowTarget?: string;
  features: ElementsFeature[];
  downloadsTitle?: string;
  downloads: ElementsDownloadRow[];
  runTitle?: string;
  runCode?: string;
  runNote?: string;
  checklistTitle?: string;
  checklistItems: ElementsStep[];
  checklistLinks: ElementsLink[];
  consoleTitle?: string;
  consoleIntro?: string;
  consoleTiles: ElementsTile[];
}

/** A sandbox access application submitted from /apply (public create; lookup by application ID + email only) */
export interface IntegratorApplication {
  applicationId?: string;
  entityType: "company_llp_firm" | "individual_proprietorship";
  organisationName: string;
  registrationNumber?: string;
  address?: string;
  contactName: string;
  email: string;
  phone: string;
  designation?: string;
  role: "provider" | "payer" | "tpa" | "hmis_vendor" | "other";
  useCases?: unknown;
  sandboxObjective?: string;
  status: "submitted" | "under_review" | "approved" | "rejected" | "on_hold";
  reviewerNote?: string;
  submittedAt?: string;
}

/** The NHCX landing page — SEO metadata plus a reorderable list of sections */
export interface LandingPage {
  seo?: ElementsSeo;
  sections?: (SectionsHero | SectionsActors | SectionsPipeline | SectionsCapabilities | SectionsSplitBenefits | SectionsLiveStats | SectionsDashboardPromo | SectionsSteps | SectionsIntegrationKit | SectionsDevtools | SectionsFaq | SectionsCta)[];
}

/** An announcement, circular, release or press mention */
export interface NewsItem {
  date: string;
  tag: string;
  tone?: "brand" | "muted";
  title: string;
  body?: string;
  meta?: string;
  url?: string;
  rank?: number;
}

/** Newsroom copy (articles are the News item collection) */
export interface NewsPage {
  seo?: ElementsSeo;
  eyebrow?: string;
  title?: string;
  intro?: string;
  featuredTag?: string;
  featuredDate?: string;
  featuredTitle?: string;
  featuredDescription?: string;
  featuredLinkLabel?: string;
  featuredUrl?: string;
  featuredImageNote?: string;
  upcomingTitle?: string;
  events: ElementsEvent[];
  upcomingNote?: string;
  upcomingLink?: ElementsLink;
  enquiriesTitle?: string;
  enquiriesText?: string;
}

/** Guided integration playbook: stages plus per-persona API lists */
export interface PlaybookPage {
  seo?: ElementsSeo;
  eyebrow?: string;
  title?: string;
  intro?: string;
  personaLabel?: string;
  stages: PlaybookStage[];
  personas: PlaybookPersona[];
}

/** One release of this site or its sandbox tooling — version, date, channel, highlights, breaking changes and links */
export interface ReleaseNote {
  version: string;
  date: string;
  channel: "sandbox" | "production";
  title?: string;
  summary?: string;
  highlights: ElementsBullet[];
  breaking: ElementsBullet[];
  links: ElementsLink[];
}

/** A sandbox component shown on the service-health tab of /status */
export interface Service {
  name: string;
  key: string;
  description?: string;
  currentState: "operational" | "degraded" | "partial_outage" | "major_outage" | "maintenance";
  order?: number;
}

/** Status page copy: service-health tab and application-status lookup */
export interface StatusPage {
  seo?: ElementsSeo;
  eyebrow?: string;
  title?: string;
  intro?: string;
  placeholder?: string;
  buttonLabel?: string;
  tryLabel?: string;
  notFoundText?: string;
  healthTabLabel?: string;
  applicationTabLabel?: string;
  healthIntro?: string;
  applicationIntro?: string;
  emailPlaceholder?: string;
  activeIncidentsTitle?: string;
  pastIncidentsTitle?: string;
  uptimeLabel?: string;
  demoLabel?: string;
}

/** A trackable reference: sandbox application or claim correlation ID */
export interface StatusRecord {
  recordId: string;
  kind?: string;
  title: string;
  state?: string;
  tone?: "ok" | "wait" | "muted";
  updated?: string;
  steps: ElementsTimelineStep[];
  facts: ElementsStatItem[];
}

/** An email address that asked for release notes (public create only; never listed publicly) */
export interface Subscriber {
  email: string;
  consent: boolean;
  source?: "footer" | "news" | "other";
  consentedAt?: string;
}

/** A recording in the library, grouped by track. Without a URL it is listed as a planned recording with its outline; webinar entries form their own group */
export interface Video {
  track: string;
  title: string;
  description?: string;
  length?: string;
  date?: string;
  url?: string;
  rank?: number;
  webinar?: boolean;
  webinarDate?: string;
  outline: ElementsBullet[];
}

/** Video library copy (videos themselves are the Video collection) */
export interface VideosPage {
  seo?: ElementsSeo;
  eyebrow?: string;
  title?: string;
  intro?: string;
  channelCta?: ElementsLink;
  featuredBadge?: string;
  featuredTitle?: string;
  featuredDescription?: string;
  featuredMeta?: string;
  featuredUrl?: string;
  footNote?: string;
  footLink?: ElementsLink;
}

// ─── Landing sections ────────────────────────────────────────────────────────

/** Every component the landing dynamic zone accepts, as a discriminated union. */
export type Section = SectionsHero | SectionsActors | SectionsPipeline | SectionsCapabilities | SectionsSplitBenefits | SectionsLiveStats | SectionsDashboardPromo | SectionsSteps | SectionsIntegrationKit | SectionsDevtools | SectionsFaq | SectionsCta;

/** The `__component` UID of any landing section. */
export type SectionUid = Section['__component'];

// ─── Snapshot ────────────────────────────────────────────────────────────────

/**
 * The shape of `content/snapshot.json` (and its committed baseline,
 * `content/fallback.json`), assembled by `scripts/sync-content.mjs`.
 */
export interface SiteContent {
  global: Global;
  landing: LandingPage;
  pages: {
    devtools: IntegrationKitPage;
    videos: VideosPage;
    news: NewsPage;
    apply: ApplyPage;
  };
  collections: {
    videos: Video[];
    newsItems: NewsItem[];
    releaseNotes: ReleaseNote[];
  };
}

/** Keys the snapshot must contain, mirrored from scripts/cms-map.mjs. */
export const PAGE_KEYS = ["devtools", "videos", "news", "apply"] as const;
export const COLLECTION_KEYS = ["videos", "newsItems", "releaseNotes"] as const;
export const SECTION_UIDS = ["sections.hero", "sections.actors", "sections.pipeline", "sections.capabilities", "sections.split-benefits", "sections.live-stats", "sections.dashboard-promo", "sections.steps", "sections.integration-kit", "sections.devtools", "sections.faq", "sections.cta"] as const;
