#!/usr/bin/env node
/**
 * Copies the parts of scripts/cms-map.mjs the CMS needs at bootstrap into
 * ../cms/data/cms-map.json:
 *
 *   sectionPopulate   the landing dynamic-zone populate tree, used by the
 *                     migrations that rewrite landing sections in place
 *   endpoints         every synced content type with its kind, from which
 *                     the CMS derives the public read permissions
 *   runtimeActions    the public write/query permissions behind the
 *                     endpoints the browser calls directly (RUNTIME)
 *
 * The CMS is a CommonJS TypeScript project compiled by Strapi into dist/,
 * and `rootDir` stops it importing a file outside its own tree; a JSON file
 * under cms/data — read at runtime like the seed files — is the simplest
 * shape both toolchains accept. This script keeps the copy honest:
 *
 *   node scripts/sync-cms-map.mjs           # write cms/data/cms-map.json
 *   node scripts/sync-cms-map.mjs --check   # fail when the copy has drifted
 *
 * `npm run check` runs the --check form, so a map edit that is not synced
 * fails the build rather than leaving the CMS on a stale populate tree.
 */
import fs from 'node:fs';
import path from 'node:path';
import { ENDPOINTS, RUNTIME_ACTIONS, SECTION_POPULATE } from './cms-map.mjs';

const ROOT = path.join(import.meta.dirname, '..');
const CMS = process.env.CMS_DIR ?? path.join(ROOT, '..', 'cms');
const OUT = path.join(CMS, 'data', 'cms-map.json');
const CHECK = process.argv.includes('--check');

const output =
  JSON.stringify(
    {
      $comment: 'Generated by landing/web/scripts/sync-cms-map.mjs from scripts/cms-map.mjs — do not edit.',
      sectionPopulate: SECTION_POPULATE,
      endpoints: ENDPOINTS.map((e) => ({ key: e.key, uid: e.uid, kind: e.kind })),
      runtimeActions: RUNTIME_ACTIONS,
    },
    null,
    2,
  ) + '\n';

if (CHECK && !fs.existsSync(path.join(CMS, 'src'))) {
  // No CMS checkout beside this project (a standalone build of the site):
  // there is no copy to compare against, and nothing here to keep honest.
  console.log(`– No CMS project at ${path.relative(ROOT, CMS)}; skipping the cms-map.json drift check`);
  process.exit(0);
}

if (CHECK) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (current !== output) {
    console.error(`✖ ${path.relative(ROOT, OUT)} is out of date with scripts/cms-map.mjs.`);
    console.error('  Run `npm run sync:cms-map` and commit the result.');
    process.exit(1);
  }
  console.log(`✔ ${path.relative(ROOT, OUT)} matches scripts/cms-map.mjs`);
} else {
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, output);
  console.log(`✔ Wrote ${path.relative(ROOT, OUT)}`);
}
