import { withBase } from '@/lib/paths';
import TypicalFlow from '@/components/landing/TypicalFlow';
import NetworkPacket from '@/components/landing/NetworkPacket';

const PROVIDERS = ['Government Hospital', 'Medical College & Hospital', 'Private Nursing Home', 'Day Care & OPD Clinics'];
const PAYERS = ['Insurance Company', 'TPA', 'State Health Agency', 'Government Scheme'];

/*
 * The provider ↔ NHCX ↔ payer network, carried over from the previous
 * landing page: each column's nodes hang off a trunk by dotted stubs, the
 * trunk meets a dashed wire that marches towards the exchange, and a
 * document travels along the wires through the exchange and back
 * (NetworkPacket).
 */

function stubClass(i: number, n: number) {
  return `how-stub${i === 0 ? ' first' : ''}${i === n - 1 ? ' last' : ''}`;
}

function Wire() {
  return (
    <div className="how-wire" aria-hidden="true">
      <div className="how-wire-line" />
    </div>
  );
}

export default function HowItWorks() {
  return (
    <section className="how" aria-labelledby="how-title">
      {/* The navy slab: the vector keeps its shape (notch, corners), and the
          band continues below it in the gradient's end colour however tall
          the pinned story makes the section. */}
      <div className="how-bgs" aria-hidden="true">
        <div className="how-shadow" style={{ backgroundImage: `url(${withBase('/assets/how-bg-shadow.png')})` }} />
        <img className="how-bg" src={withBase('/assets/how-bg-vector.svg')} alt="" />
        <div className="how-fill" />
      </div>

      <div className="wrap how-block">
        <h2 className="vh" id="how-title">How NHCX works</h2>
        <div className="how-body">
          <div className="how-intro">
            <p className="how-lede">
              Idea is to transmit the health information that is already generated by a Provider hospital in digitized format to an Insurer without losing any of its essence,{' '}
              <span>and that too in a protocol standard set by the Payer beforehand.</span>
            </p>
            <a className="btn btn--primary" href={withBase('/docs/')}>View Docs →</a>
          </div>

          {/* wide: the two columns wired through the hub */}
          <div className="how-net" role="img" aria-label="Providers such as hospitals, nursing homes and clinics exchange documents with payers such as insurers and government schemes through NHCX">
            <div className="how-side is-provider">
              <p className="how-col-label">Provider</p>
              <div className="how-grid">
                {PROVIDERS.map((p, i) => (
                  <div key={p} style={{ display: 'contents' }}>
                    <div className="how-node">{p}</div>
                    <div className={stubClass(i, PROVIDERS.length)} aria-hidden="true" />
                  </div>
                ))}
              </div>
            </div>
            <Wire />
            <div className="how-hub">NHCX</div>
            <Wire />
            <div className="how-side is-payer">
              <p className="how-col-label">Payer</p>
              <div className="how-grid">
                {PAYERS.map((p, i) => (
                  <div key={p} style={{ display: 'contents' }}>
                    <div className={stubClass(i, PAYERS.length)} aria-hidden="true" />
                    <div className="how-node">{p}</div>
                  </div>
                ))}
              </div>
            </div>
            <NetworkPacket />
          </div>

          {/* narrow: stacked */}
          <div className="how-stack" aria-hidden="true">
            <p className="how-col-label">Provider</p>
            <div className="how-stack-grid">
              {PROVIDERS.map((p) => (
                <div key={p} className="how-node">{p}</div>
              ))}
            </div>
            <div className="how-vwire" />
            <div className="how-hub">NHCX</div>
            <div className="how-vwire" />
            <p className="how-col-label">Payer</p>
            <div className="how-stack-grid">
              {PAYERS.map((p) => (
                <div key={p} className="how-node">{p}</div>
              ))}
            </div>
          </div>
        </div>
      </div>

      <TypicalFlow />
    </section>
  );
}
