name: Build & Deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Configure AWS - Production
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Configure AWS - Development
        if: github.ref == 'refs/heads/develop'
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy Production
        if: github.ref == 'refs/heads/main'
        run: |
            aws s3 sync dist/ s3://${{ secrets.PROD_S3_BUCKET }}/ --delete
    
      - name: Deploy Development
        if: github.ref == 'refs/heads/develop'
        run: |
            aws s3 sync dist/ s3://${{ secrets.DEV_S3_BUCKET }}/ --delete
